account_type: aws
bucket_key: fdfdfdsda
bucket_secret: dasdasd
bucket_url: dasdas
database_host: localhost
database_port: 19530
database_service: milvus
milvus_alias: default
milvus_collection_name: collection
device: cpu
run_mode: debug
supported_account_types:
- aws
