version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    command: ["npx", "vite"]

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:imagesearch", "--host", "0.0.0.0", "--port", "8000"]

