account_type: aws
bucket_key: m1ejnalbyzjylSnQcr0j
bucket_name: image_search_bucket
bucket_secret: DWEXLY6tDF4HHZI9tqob84eenK4s2Tm3TcLArOub
bucket_url: https://services-inteliome.yco.c"om.np:8741
database_host: localhost
database_port: 19530
database_service: milvus
device: cpu
milvus_alias: default
milvus_collection_name: collection
run_mode: debug
supported_account_types:
- aws
